# Generated by Django 5.2.10 on 2026-03-26 12:44

import common.vaidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[common.vaidators.validate_image_size]),
        ),
    ]
