# Generated by Django 5.2.10 on 2026-03-15 20:20

import common.vaidators
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='Anonymous', max_length=50)),
                ('body', models.TextField(validators=[common.vaidators.validate_review_body])),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('is_verified', models.BooleanField(default=False)),
                ('review_type', models.CharField(choices=[('Text', 'Text'), ('Video', 'Video'), ('Audio', 'Audio')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shoe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shoes.shoe')),
            ],
        ),
    ]
