# Generated by Django 5.2.10 on 2026-02-23 11:14

import common.vaidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_review_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='body',
            field=models.TextField(validators=[common.vaidators.validate_review_body]),
        ),
    ]
