# Generated by Django 5.2.10 on 2026-03-15 20:20

import common.vaidators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Nike', 'Nike'), ('Champion', 'Champion'), ('New Balance', 'New Balance')], max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=10)),
                ('size', models.IntegerField(blank=True, choices=[(37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45')], null=True)),
                ('color', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('is_available', models.BooleanField(default=True)),
                ('description', models.TextField(validators=[common.vaidators.validate_description_length])),
                ('image', models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[common.vaidators.validate_image_size])),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='shoes', to='shoes.category')),
            ],
        ),
    ]
