# Generated by Django 5.2.10 on 2026-02-10 21:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='model',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='sport',
            field=models.CharField(blank=True, choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Handball', 'Handball')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(choices=[('Adidas', 'Adidas'), ('Puma', 'Puma'), ('Nike', 'Nike'), ('Champion', 'Champion'), ('New Balance', 'New Balance')], max_length=100),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(blank=True, choices=[(38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44')], null=True),
        ),
    ]
