# Generated by Django 5.2.10 on 2026-03-23 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('running', 'Running'), ('indoor', 'Indoor'), ('outdoor', 'Outdoor'), ('court', 'Court'), ('lightweight', 'Lightweight')], max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='category',
            name='sport',
            field=models.CharField(blank=True, choices=[('football', 'Football'), ('volleyball', 'Volleyball'), ('basketball', 'Basketball'), ('handball', 'Handball')], max_length=50),
        ),
        migrations.AddField(
            model_name='shoe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='shoes', to='shoes.tag'),
        ),
    ]
