# Generated by Django 5.2.10 on 2026-02-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_shoe_model_shoe_sport_alter_shoe_brand_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Handball', 'Handball')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='sport',
        ),
        migrations.AddField(
            model_name='shoe',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='shoes', to='shoes.category'),
        ),
    ]
