# Generated by Django 5.2.10 on 2026-02-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_alter_category_id_alter_shoe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='sport',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='categories',
            field=models.ManyToManyField(blank=True, choices=[('Football', 'Football'), ('Basketball', 'Basketball'), ('Volleyball', 'Volleyball'), ('Handball', 'Handball')], related_name='shoes', to='shoes.category'),
        ),
    ]
