# Generated by Django 5.2.10 on 2026-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0005_alter_category_sport_alter_shoe_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='shoes', to='shoes.category'),
        ),
    ]
