# Generated by Django 5.2.10 on 2026-02-18 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0006_alter_shoe_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='gender',
            field=models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Unisex', 'Unisex')], default='Unisex', max_length=10),
        ),
    ]
