# Generated by Django 5.2.10 on 2026-02-18 10:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('shoes', '0007_shoe_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoe',
            name='account',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='shoes', to='accounts.account'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(blank=True, choices=[(37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45')], null=True),
        ),
    ]
