# Generated by Django 5.2.10 on 2026-02-23 11:14

import common.vaidators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0007_shoe_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='description',
            field=models.TextField(validators=[common.vaidators.validate_description_length]),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='post_images/', validators=[common.vaidators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.IntegerField(blank=True, choices=[(37, '37'), (38, '38'), (39, '39'), (40, '40'), (41, '41'), (42, '42'), (43, '43'), (44, '44'), (45, '45')], null=True),
        ),
    ]
