# Generated by Django 5.2.10 on 2026-02-18 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0008_shoe_account_alter_shoe_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='account',
        ),
    ]
